name: Build Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Pack extension
      run: |
        mkdir -p build
        zip -r build/extension.zip . -x '*.git*' -x '*.github*' -x 'node_modules/*'
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: chrome-extension
        path: build/extension.zip