name: Build Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Pack extension
      run: |
        mkdir -p build
        zip -r build/extension.zip . -x '*.git*' -x '*.github*' -x 'node_modules/*'
      
    - name: Publish to GitHub Packages
      run: |
        mv chrome-extension/extension.zip chrome-extension.zip
        echo "name=chrome-extension" >> $GITHUB_ENV
        echo "version=0.0.1" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v0.0.1"
        release_name: "Chrome Extension v0.0.1"
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/extension.zip
        asset_name: chrome-highlight-github-workflows.zip
        asset_content_type: application/zip